### ISSUE TITLE
Spyglass doesn't work

### ISSUE THREAD

**Issue by fholger** [fholger/thedarkmodvr#16]
All it does is place a spyglass cutout on the UI overlay, no actual zooming or anything.

Not sure how to best approach the spyglass in VR; I'm afraid it might need a very different approach, which could make it time-consuming to implement.

Currently very low priority.

**Comment by fholger** [comment]
I've decided to force the spyglass to render in 2D, i.e. when you activate the spyglass, the game is rendered to the UI overlay. Not the greatest of solutions, but it was fairly simple to do, and it at least makes the spyglass function in some capacity.

I did also try to just zoom the normal eye views, but I must admit the math to do so is beyond me. The spyglass zoom is done by decreasing the vertical FOV in the game. However, VR headsets use asymmetrical projections, meaning instead of a vertical and horizontal FOV angle, you have 4 angles for left, right, up and down. I have no idea how to adjust those 4 to end up with a zoomed view that doesn't look or feel wrong in some way, if that's even possible. If anyone knows more than I do, I'm happy for any hints :)

**Comment by LaoGaoBeBePao** [comment]
Please add cvar to disable an auto zoom animation. Or, if it already exists, add it in TDM-VR "Advanced settings" page.  

Auto-zoom is "on" by default and feels bad. I will prefer to use "alt+mouse-scroll" to zoom.
Maybe it needs to be set to minimum zoom by default.

**Comment by LaoGaoBeBePao** [comment]
I tested the last fix (vr_disableZoomAnimations).
Now is better. But the game is flicker after I exit from spyglass mode. For a half of a second (Or less) I see the UI window with a small image from the zoom, without a spyglass cutout.

**Comment by fholger** [comment]
Yes, there is approximately one frame or so where the non-spyglass view is rendered to the UI. That has to do with the way the spyglass works - it is entirely controlled by scripts, and to even know that it's active, I have to query a side-effect from the script execution. That side effect is unfortunately the last thing to be removed, so...

In short, I'm not going to fix this at this time, because to do so I would have to mess with the scripting system, which is too much effort for a fairly minor glitch :) Might revisit this at a much later stage when I will have to deal with scripting.
