### ISSUE TITLE
Left and right leans cause motion sickness

### ISSUE THREAD

**Issue by LaoGaoBeBePao** [fholger/thedarkmodvr#26]
Need to disable the camera turns and leave only the change of position.

**Comment by fholger** [comment]
I'm not sure if that might not look very weird. But there are definitely a couple of other places that cause the camera to move, e.g. mantling over obstacles or getting hit by enemies. Since you can just not use lean, I think those are probably more important to address for now?

**Comment by LaoGaoBeBePao** [comment]
>Since you can just not use lean

Without leans some loot will be unreachable because the player can't frob it.
As example - FM "The Crown of Penitence", flashbomb in the locker.

>I'm not sure if that might not look very weird. 

If I lean in real life I bend my neck and keep my head stand straight. Because I do not want my head (Or hood on the head) came around the corner.
So without the rolls axis leans will be more realistic.

The problem is that camera animation do tilts the floor. At now leans is "look very weird".

>mantling over obstacles or getting hit by enemies.

Mantling is not a problem because the camera do not "roll" this much.

I suggest that the best decision is totally disable the roll axis from animations. Leans/mantling will be better.

**Comment by fholger** [comment]
Done in alpha 4.
