### ISSUE TITLE
The bow is unusable

### ISSUE THREAD

**Issue by LaoGaoBeBePao** [fholger/thedarkmodvr#27]
At now a camera and hand with a bow is decoupled. So I can't predict where an arrow will hit.
New "VR frob helper point" is not helping much.
Need some path visualisation. Not like a straight laser but like in SkyrimVR (The Eagle Eye skill but without crosshair).

**Comment by fholger** [comment]
The aim indicator works fine for me with the bow? Perhaps this is due to your seated position not being correctly calibrated, but for me, the dot is a very good indicator where the arrow will go...

**Comment by fholger** [comment]
Is this still an issue? I feel that if your seated position is properly calibrated, the aim indicator does give a good indication of where the arrow is going, and the rest is practice (even in the flat game, it takes some getting used to...)

**Comment by LaoGaoBeBePao** [comment]
>Is this still an issue?

Not for short and middle distances. But at long range I can miss in "left-right" directions, not just "up-down" like in flat TDM.

I understand that problem is all about how "seated experience" is implemented. How mouse and VR-view is decoupled and how the game mechanics are working. Not just implementation of the bow.
At now TDM-VR is required player to be stay synchronized with in-game position. So much synchronize is required that it was more convenient for me to shoot when my WMR position tracking is stop working (Due of turn off lights in the my room). In this mode my HMD only tracks yaw-pitch-roll axis (Like Oculus DK1) and HMD stay completely synchronized with in-game position.

For now is the best you can do is try to disable depth limit for the vr-pointer when the bow is active (Or when the bow is ready to shoot). So the player will not fight with desynchronization that can be after long play (I am a living being, so my body is moving even if I seating).
I will just see in what "left-right" directions I shoot. Without using "reset seated position" button when I want to shoot long range targets.
For now I need to use "win" button or alt-tab to free the cursor from TMD window and get access to the SteamVR window. Or powerup a motion controllers and access SteamVR from VR. Or just save-load a lot and shoot without reset.

VR-pointer with disabled depth limit will allow to shoot at long range targets without cheating or easy shots (Like if the "Eagle Eye" from SkyrimVR will be implemented). Because the player is needed to not forget about gravity when shooting.
And this will not look weird like some "laser" from the bow.

May be then you also need to make the vr-pointer stay at the same size (From view point) at all distances.

**Comment by fholger** [comment]
The aim indicator will now go further when the bow is drawn, and also be drawn slightly larger. The range and size is configurable with `vr_aimIndicatorRangedMultiplier` and `vr_aimIndicatorRangedSize`. This should hopefully allow you to find some settings that work for you. I don't think I can do any more for this.

**Comment by LaoGaoBeBePao** [comment]
The indicator does not change size at short and long distances. So it big at short and small at long distance. It does not "stay at the same size (From view point) at all distances".

Although the bow is working fine enough now. I can use it even if I lean in real life.
Thanks you.

**Comment by fholger** [comment]
Yes, that's intentional and happens kind of automatically by the view projection of the indicator. To uncouple its size from distance would take some effort. And it might actually mess with depth perception, because things getting smaller in the distance is a part of what makes things appear farther away.
