### ISSUE TITLE
Player visibility based on HMD position (Not on body position)

### ISSUE THREAD

**Issue by LaoGaoBeBePao** [fholger/thedarkmodvr#28]
I do not know bug or feature is it. The player can put head in a wall or shadow and be invisible even nearby light source.
Possibly it good for a room-scale game, but now the player can cheat with that. Or can experience unpredictable visibility changes (If he plays without proper position calibration).

**Comment by fholger** [comment]
Hm, technically, the head position does not affect the player location in the game, so this sounds like a bug. However, depending on what causes it, it may not be easy to fix. The issue could be either that the lightgem rendering accidentally takes the wrong position (which would be easy to fix), or that selection of what lights and shadows to render is based on the main view, in which case it's much harder to fix and I may leave it as it is.

In general, though, the seated experience does assume that your head remains more or less in your natural position, and you can indeed cheat by moving physically away and e.g. look through walls and other stuff. This is not something I'm going to address for the seated experience, and I'll have to see what I can reasonably do once I move to a room-scale experience.

**Comment by LaoGaoBeBePao** [comment]
Tested it again. Is not the lightgem. Guard can't see me if I put my head in a wall. He loses me even if he saw me before.

**Comment by fholger** [comment]
Found it, the lightgem was indeed accidentally taking the headset position into account. Will be fixed in the next alpha, thanks for reporting it!
