### ISSUE TITLE
Rotation / body position seems to be based on center of room

### ISSUE THREAD

**Issue by blamarche** [fholger/thedarkmodvr#3]
Your body position seems to be based on center of room, which if your chair/desk are not exactly in makes rotation with the mouse feel like you're on a merry-go-round. It'd be good to calibrate the player's position based on where the headset was when the mission was started. The Oculus Home 'reset my position' doesn't appear to affect this game.

**Comment by fholger** [comment]
No, it's actually based on what SteamVR considers your seated position. You can reset it in the SteamVR menu. When I get to the point of actually adding custom configuration options and controls, I might add a shortcut from within the game to do this. Or I might skip it entirely and go directly for roomscale :)

**Comment by blamarche** [comment]
Ah okay. Cool, I wasn't aware of the SteamVR reset, thanks!
