### ISSUE TITLE
White mirror screen

### ISSUE THREAD

**Issue by LaoGaoBeBePao** [fholger/thedarkmodvr#31]
Sometimes mirror screen going stuck and slowly going to fully white.
(Maybe game do not properly clean up information from the previous frame and just keep adding RGB value from new frame?)

**Comment by fholger** [comment]
Can you reproduce this behavior in some way? I've never seen it... What GPU do you have? Are you using the SteamVR or the OpenXR backend?

**Comment by LaoGaoBeBePao** [comment]
>Can you reproduce this behavior in some way? 

Easy. Just start FM "Accountant 1: Thieves & Heirs".
Funny, but I can run TDM-VR without HMD and SteamVR. And bug will reproduce like when I use HMD. In this mode the head in a ceiling (Again!) but my view is normal. If I toggle crouch (So my view will be in the room) and observe the room, then screen going white.
In VR all the same. But instead of ceiling I used a wall.

New found - if I pick up lockpick in inventory, then mirror screen is going back to normal behavior. After I clear the inventory screen is going to white.

>What GPU do you have? Are you using the SteamVR or the OpenXR backend?

Windows 1809, GTX1060 (6gb), driver 446.14, SteamVR  1.13.10, SteamVR backend.

>or the OpenXR backend?

OpenXR backend is not working. Game crash.

**Comment by fholger** [comment]
I'm afraid I cannot seem to reproduce this. Is it only happening when your head is stuck in a ceiling/wall?

Out of curiosity, how is performance for you? There are scenes in some missions where even my RTX 2080Ti cannot prevent reprojection, so I'm curious how playable it is on a 1060 :)

**Comment by LaoGaoBeBePao** [comment]
Your last fix is working. Now I can't reproduce this bug in FM "Accountant 1: Thieves & Heirs".

>Is it only happening when your head is stuck in a ceiling/wall?

No.
Previously, in FM "Accountant 1" ceiling/wall is only allowing me to control this bug. Turns bug on/off immediately. If I observe the room, at some angle of view, this bug turns on-off too (Random?).

>Out of curiosity, how is performance for you? There are scenes in some missions where even my RTX 2080Ti cannot prevent reprojection.

Oh, don't worry. If the game is rendered under 45 fps reprojection is not working. So I not have any problem with reprojection.

(Lol)

In what FM I should test performance? Some FM is a little bit choppy, but it not critical for me.
Do not tested many FM yet. For now I walk through FM "Requiem" without any serious problems.

**Comment by fholger** [comment]
Great that the bug is fixed.

As a base line, the included missions (training and mission 1+2) are generally not too taxing, so if those are playable, that'd be a good sign. Obviously, some missions have really poor performance (e.g. Briarwood Manor).
