### ISSUE TITLE
Texts in books are transparent.

### ISSUE THREAD

**Issue by LaoGaoBeBePao** [fholger/thedarkmodvr#32]
I can see the background (Walls, torches, etc.). Difficult to read if the background is light.
May be related to "black alpha channel" issue.

**Comment by LaoGaoBeBePao** [comment]
The bug affected by place. In some places texts are normal and in some is not. Used the same note to test it.
The bug can be replicated in FM "Training mission" (First book) and in FM "Requiem" (A note in the basement).
(Shaders?)

**Comment by fholger** [comment]
Already tracked as #21 
Unfortunately, the UI elements are rendered with transparency, and there may not be much I can do about it, as these may be mission-specific materials that I cannot globally fix. If I can improve it, I certainly will.

**Comment by LaoGaoBeBePao** [comment]
It's because symbols are black? Can you change color of fonts? Make it gray, not black.
