### ISSUE TITLE
Possibility to use the same saves for flat and VR TDM

### ISSUE THREAD

**Issue by LaoGaoBeBePao** [fholger/thedarkmodvr#35]
I want immerse myself to the mission with VR and, after FM is going to end, use my monitor and flat TDM to find last secrets or pieces of the loot.
Because it's too difficult to stay in VR for hours just for finding a last 25 gold in FM that have 10000 gold in loot.
Previously I tried to load saves and the flat version is rejecting to use saves from "version 0" of the game.

VR TDM is "2.09.47" (Nightly build). Seems I need to obtain and use "2.09 alpha" TMD cause at now my copy of the flat version of the game is "2.08". But "version 0" issue will remain, I'm right?

It's possible? If the VR version is different in "how is rendered", but not in the game mechanics/in-game position/other?

**Comment by fholger** [comment]
There's a cvar `tdm_force_mission_load`. If you set that to 1, the game will allow you to load the saves, despite warnings. There shouldn't be any particular issues that I could think of, but, obviously, no guarantees :)

**Comment by LaoGaoBeBePao** [comment]
I will test it. Thanks.

**Comment by fholger** [comment]
I'm going to assume this works, so I'm closing this issue.

Btw, if you do face some issues with savegame compatibility, one option would be to use a dev build for the flat game, which is going to be closer to the VR version than 2.08. You can install dev builds with the tdm_installer: https://forums.thedarkmod.com/index.php?/topic/20460-new-tdm_installer-and-dev-builds/

You will probably still need to set the mentioned cvar, though.

**Comment by wingfixer** [comment]
I'm not sure if it was different before, but the variable is actually `tdm_force_savegame_load` in latest.
