### ISSUE TITLE
(Feature request) Using HMD up-down direction when climbing ladders.

### ISSUE THREAD

**Issue by LaoGaoBeBePao** [fholger/thedarkmodvr#37]
When I first started to play TDM-VR I was keep trying to climbing ladders with my head/view direction. It's a habit from other games.
Another problem is I am losing the vr-mouse-pointer. Because this pointer is not staying in my field of view, he may go to up or down.

At now this habit is almost gone. But I keep losing the vr-mouse-pointer. So climbing is problematic sometimes. 

Can you remap climbing behavior from a vr-mouse-pointer to HMD? Maybe add a another cvar. Maybe with cvar's for angles (So I will can adjust at what angles I will climb up/down).

HMD view is pointing to "up" or "down" direction in any position of a position tracking. So it will be no problems with angle detection, even if HMD is placed in a couple meters from in-game position.
It will work without conflicts with already existing game mechanics or VR implementation.

Another solution is to set the vr-mouse-pointer to stay in the field of view, like in Quake2VR. It will improve all climbing, not only ladders and ropes.
But, obviously, it required completely rework mouse emulation logic (Set "point of the start of the mouse" moving with HMD).

**Comment by fholger** [comment]
At the moment, head rotation/position has no effect whatsoever on any gameplay mechanics (or if it does, it's probably a bug). Obviously, that's not ideal; not just for ladders, but potentially other things, as well. For example, movement in general is tied to the mouse position, so "forward" may not be the direction you expect even off ladders.

This will eventually have to change, but this will take time as it ties into a lot of gameplay elements. In the meantime, I can certainly look into "trapping" the mouse cursor in the current view.

**Comment by fholger** [comment]
I will probably not make any significant changes to the keyboard+mouse/gamepad experience anymore unless absolutely necessary. For motion controller input, the direction of movement will be relative to either the controller or head orientation, which is also respected when climbing ladders.
