### ISSUE TITLE
At certain angles, shadows aren't being drawn fully or at all in one eye

### ISSUE THREAD

**Issue by blamarche** [fholger/thedarkmodvr#4]
In one eye, in some lighting situations the shadows aren't being drawn at all. In others, only some of the shadow is being drawn. Both of these cause an uncomfortable flickering effect whereever present. GTX 970.

**Comment by fholger** [comment]
Yep, that's the most pressing issue right now (it's listed in the known caveats). So far, I have no clue what's causing it.
(It's not just shadows, though. Some other surfaces also show similar behaviour.)

**Comment by fholger** [comment]
I found a workaround. Put the following in your autoexec.cfg:
```
set r_useLightScissors 0
set r_useClippedLightScissors 0
set r_useInteractionScissors 0
```

Might cost some performance, though. I'm going to investigate why these scissors are broken and if there's a smarter way than turning them off.

**Comment by blamarche** [comment]
Cool! I'll check it out
