### ISSUE TITLE
Screenshot feature (F12) is broken

### ISSUE THREAD

**Issue by LaoGaoBeBePao** [fholger/thedarkmodvr#41]
(Not the critical issue)
Seems TDM-VR creates a screenshots with dimensions from the resolution of the supersampling. My screenshots are a 1684x1680 pictures. But TDM-VR do not scale an image to this size. So the screenshots look like a black square with a smaller image in the left-down corner.

**Comment by LaoGaoBeBePao** [comment]
Found why the image is smaller that its need to be. It is the resolution of the window that appear on the monitor.
So, if I set this window to be 640x480, then the image will be even smaller that before.

**Comment by fholger** [comment]
Should hopefully be fixed in alpha 6.

(Savegame preview images seem to also be broken, but that's a different issue, unfortunately.)
