### ISSUE TITLE
WMR/HP reverb - UI elements are vertically misaligned

### ISSUE THREAD

**Issue by blamarche** [fholger/thedarkmodvr#42]
The light gem, for example, in one eye is about one full light gem's height offset above where it is in the other eye.

The Reverb is one of the few headets with a pure square per-eye resolution with the values as 2160x2160, maybe has something to do with it?

If theres any commands or logs I can send that would be helpful please let me know!

**Comment by fholger** [comment]
Hm, the lightgem is rendered to an overlay texture, so technically the runtime (SteamVR or WMR) is responsible for rendering that correctly on both eyes. Are you using the SteamVR or the OpenXR runtime? You could try to test the other one by adding a line `set vr_backend 0` or `set vr_backend 1` in the `autoexec_vr.cfg` file. Create it if you don't have one.

**Comment by blamarche** [comment]
Unfortunately, that gives me "XR_KHR_opengl_enable extension is required, but not supported" trying to use Microsoft's XR native support. Switching steamvr to the XR runtime I still have the same issue. Its interesting because the menus are just fine, and during the "press attack to start mission" screen the lightgem is in the correct place in both eyes, as is the message itself. Once I press attack and the 3d rendering starts its not aligned right. Its also possible the 3d world itself isn't rendering quite right, but my eyes are able to adjust for it more. Everything does feel a little... off, in the world.

**Comment by blamarche** [comment]
It works just fine using the Quest 2 via SteamVR

**Comment by fholger** [comment]
You can try this nightly build, it should work with the WMR runtime: https://ci.appveyor.com/api/buildjobs/ws85hv7p06ewxruf/artifacts/TheDarkModVR.7z

While a misaligned 3D view could, in principle, be my fault, a misaligned UI overlay really is out of my control. :(

**Comment by blamarche** [comment]
OpenXR appears to work correctly with that nightly and the view is fixed! Though I can't figure out a way to recenter my view in VR now so my head is through the roof! I don't think WMR's interface has a reset position built in, unlike steam.

PS: Via SteamVR its still messed up. I can confirm thats its not just the UI layer but also the 3d stereo rendering that is vertically offset in one eye.

**Comment by fholger** [comment]
You'd probably have to switch your room setup to a seated experience, WMR doesn't appear to offer a different way to define the seated position. Not ideal.

When I eventually include roomscale support, there will also be an ingame option to recenter, but in the meantime I'm afraid I have no further workarounds to offer.

**Comment by blamarche** [comment]
Oh thats fine, I'm just glad its working! If I don't start the game until I'm seated in my actual playing position, it centers correctly so its playable :)
