### ISSUE TITLE
(Feature request) Sharpening and saturation adjust 

### ISSUE THREAD

**Issue by LaoGaoBeBePao** [fholger/thedarkmodvr#43]
Hello.

Please add support of a sharpening shader.
Something similar to the "Contrast Adaptive Sharpener":
https://www.nexusmods.com/skyrimspecialedition/mods/38219
https://gist.github.com/martymcmodding/30304c4bffa6e2bd2eb59ff8bb09d135

It may improve performance - low supersampling can be compensated with a sharpening.
With GTX 1060 I have 30+ FPS in some missions, so, if I set super-sampling to lower level and compensate it, then maybe I will reach ~45 FPS (And reprojection will work again).

Also, the option to increase color saturation may be very useful.
Usually, I increase saturation in any game if I can (My first HMD is based on an OLED screen, and HMD that I use now is based on LCD - color not so good).
Already existed "desaturation" config line can't handle parameters like "-0.20", so I can make my game black-and-white (With "1.00"), but can't make it more colorful.

**Comment by fholger** [comment]
Good call! I added Marty McFly's version to our postprocessing stage, and the results are surprisingly good. Even at default resolution. I guess TDM's textures are a little blurry to begin with, so this helps with that...

As for saturation, the cvar value was clamped to the (0, 1) range in code. I've relaxed it to (-1, 1). You can give it a try.

**Comment by LaoGaoBeBePao** [comment]
All working as intended, thanks you.

However, it's didn't resolve a performance issue - if I set the resolution to an even lower level than the image will be horrible (Strong aliasing) and CAS didn't help much.
But I got a better image quality at my usual res.

**Comment by fholger** [comment]
For performance, on the latest master you can try shadow mapping. Switch to it in the menu, leave soft shadows off. Then you should also set `r_shadowMapSinglePass 1` or `r_shadowMapSinglePass 2`. This should generally improve performance, at least in my testing. Whether 1 or 2 is better depends on the map and scene, so you'll have to experiment a little. 2 is the more experimental mode, so it might also produce the occasional glitch. And, of course, the game and maps were originally designed for stencil shadows, so shadow maps may occasionally give strange or poor shadows. But for the most part, they work fine and are faster in VR :)

**Comment by LaoGaoBeBePao** [comment]
No, now performance even worse.

1 = just worse.
2 = horrible lags.

**Comment by fholger** [comment]
What maps? Try with 'A new job', if it's not better there, then something's off. Try deleting the darkmod_vr.cfg to ensure there are no weird settings.
