### ISSUE TITLE
Image is distorded  while moving

### ISSUE THREAD

**Issue by netshaman** [fholger/thedarkmodvr#54]
Looking left or right leads to horrible distorsions of the image .
Tried with open composite and steam VR api's.
And this leads to a headache after a while ^^
P.S: Using an Oculus  Rift S.

**Comment by fholger** [comment]
Something is broken when using the SteamVR backend with Oculus or WMR headsets, and I don't know why.

The good news is that TDM VR has an OpenXR backend, so you can actually bypass SteamVR and play natively on Oculus. In fact, I'm removing the SteamVR backend in the next release. To switch now, see here: https://github.com/fholger/thedarkmodvr/wiki/Advanced-settings#choosing-the-vr-backend

**Comment by netshaman** [comment]
Thank you , i will try this. :)

**Comment by fholger** [comment]
Since I haven't heard back, I'll assume the Oculus backend fixed this. :)
