### ISSUE TITLE
Beta 1 works, released 2.0.9 doesn't 

### ISSUE THREAD

**Issue by Patola** [fholger/thedarkmodvr#55]
ArchLinux 5.11 Radeon RX 6800 XT, Valve Index, Ryzen 7 3700 32 GB RAM and about 200 VR games on Steam working. SteamVR beta, supporting OpenXR 100%.
Last version of the Dark Mod VR (2.0.9 beta) works. Released version 2.0.9 doesn't.
gist of HW config: https://gist.github.com/Patola/6caf42ff20f69f1bc95b527ef7714a31

Attached are the text outputs of 2.0.9 final (not working) and 2.0.9 beta (working). 
[output-darkmod-209-final.log](https://github.com/fholger/thedarkmodvr/files/6058624/output-darkmod-209-final.log)
[darkmod-209-beta-working.log](https://github.com/fholger/thedarkmodvr/files/6058631/darkmod-209-beta-working.log)

**Comment by fholger** [comment]
A call to glCreateProgram fails, that's odd. From my understanding, that basically only happens if there's no GL context. Sounds as if the OpenXR runtime is "stealing" it. I can probably reset it, but that sounds like a bug in SteamVR.

**Comment by Patola** [comment]
What can I do to help? I can promise to test as fast as possible if you communicate through this bug report.

**Comment by fholger** [comment]
I'm almost certain it's this issue: https://github.com/ValveSoftware/SteamVR-for-Linux/issues/421
I'm afraid there's nothing for you to do at the moment. Hopefully Valve fixes this issue. I can potentially work around it, but I'd rather avoid that if at all possible.

**Comment by Patola** [comment]
But it is something that appeared on the transition from the beta to the released version. What did cause it? The beta works.

**Comment by fholger** [comment]
Because the beta still had the OpenVR backend and was using it by default. This has been removed, and OpenXR is now the only backend available. If you use the beta and add `set vr_backend 1` to your autoexec_vr.cfg (to make it use the OpenXR backend), it will almost certainly fail in the same manner.

**Comment by Patola** [comment]
Tried it. Indeed, it failed. D*mn. :-(

I understand it's a steamvr bug but Valve sometimes takes years to fix these. Even the power management and camera bugs from 2017 are not yet fixed. Couldn't you create a temporary workaround to allow for more people to play the game? I am specially interested in following the development of the VR inputs.

**Comment by fholger** [comment]
Only as a last resort, as I don't really have a Linux VR environment readily available to test with and the effort would thus be relatively high.

For now, the final release isn't too different from the beta, so you can keep playing with that. The motion control stuff is still some time away.

**Comment by fholger** [comment]
I have implemented workarounds for this in the latest commits. I'm not really convinced that the Linux OpenXR implementation is solid and can provide a good experience, but it works in principle...

**Comment by Patola** [comment]
Thank you very much, will be testing soon. Can we expect a new release in the next days?

**Comment by fholger** [comment]
I still have some things to take care of before the next release, so can't promise anything.

**Comment by Patola** [comment]
So, any news on that? :D
