### ISSUE TITLE
Multiple mod keys

### ISSUE THREAD

**Issue by NikhilSaini38** [fholger/thedarkmodvr#56]
Not sure if this feature is present or not, I couldn't find it in gamepad wiki.
I was wondering if mod key can be configured, and can we have multiple mod keys for a gamepad. I created a rwasd profile. Ever since last update gamepad functionality has started to interfere with my [rewasd profile](https://www.rewasd.com/community/config/the-dark-mod-controller-support/90efa082c8ea1a40290911fa153b0afc). And i know neither how to disable gamepad extension of the game nor how to configure it to my liking.

**Comment by fholger** [comment]
You can configure the modifier via `bindPadButton MODIFIER xxx` in the config file. There is only support for one modifier, and support for more is not planned. There is, unfortunately, no way to disable gamepad input at the moment; perhaps that's something for a future version.

**Comment by NikhilSaini38** [comment]
Thanks, closing.
