### ISSUE TITLE
Please have good news 😃

### ISSUE THREAD

**Issue by d0x360** [fholger/thedarkmodvr#58]
I didn't notice this project before but now that I did I need to play it...

Did you manage to get motion controls working with the game?  No small feat if you did.  It's not like the game or engine was designed with VR in mind.

That reminds me... I need to look if someone made a Dishonored 1or 2 but hopefully 1 mod.  I can do amazing things in those games and I can only imagine what it would be like in VR!  

It's like I was born with Corvo's abilities and I don't even play it with MKB, I've just played it THAT much.

**Comment by fholger** [comment]
This project is currently on hold while I'm working on Half-Life 2 VR. Can't do both at the same time :) I do intend to return to it after HL2.

**Comment by d0x360** [comment]
That sounds fantastic too!  I haven't played HL2 since launch or close to
launch anyways.

The VR modding community is on fire!

**Comment by Crimson-foxGITHUB** [comment]
@d0x360 since you asked from the other repo: 1183-economyfuel#6448

**Comment by fholger** [comment]
FYI, I did release a small update to bring the mod on par with the base 2.10 version that was released earlier this year. No new VR features, though :)

**Comment by d0x360** [comment]
I'll still give it a look.  I don't mind early versions of software.  I was a tester for sega, id and epic many years ago and I also had an oculus DK1 & DK2 and they were rough lol... Especially the dk1.
