### ISSUE TITLE
Not working with new tdm 2.06

### ISSUE THREAD

**Issue by Hoshi82** [fholger/thedarkmodvr#7]
Is there a way to get the old 2.05 version, or better an update for the vr mod? :)

**Comment by nbohr1more** [comment]
To get 2.05, you can download 2.0 from here:
https://www.moddb.com/mods/the-dark-mod/downloads

then run tdm_updater and stop after it completes the 2.04 to 2.05 update step.

You can also manually patch via the 2.0 to 2.01 > 2.01 to 2.02 etc patches at the same download site.

**Comment by fholger** [comment]
Update will come eventually, but it's going to take some time.

**Comment by cercata** [comment]
Still comming that update ?

**Comment by fholger** [comment]
No, sorry, at least not any time soon. The engine simply doesn't perform as well as I need it to make a full VR port truly viable, and until that changes, I can't justify to myself spending more time on this. Sorry :(

**Comment by cercata** [comment]
In some years the engine will be better and our computers faster ... I hope it will come to an end.
Never is too late for a good clasic on VR, so launch on 2023 would be perfect

**Comment by cercata** [comment]
So does the engine perform better now ? Eager to try it !!!!

**Comment by fholger** [comment]
Yes, significantly, although there are still some VR-specific issues I need to solve.
